services:
  uart:
    image: uart-rx:dev
    container_name: uart_rx
    privileged: true
    working_dir: /work
    volumes:
      - /home/torizon/projects/toradex/toradex-modular:/work
    devices:
      - /dev/ttyS0
      - /dev/ttyS1
      - /dev/ttyUSB0
      - /dev/ttyACM0
    stdin_open: true
    tty: true
