FROM --platform=linux/arm64 debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        entr \
    && rm -rf /var/lib/apt/lists/*

# Optional but nice:
WORKDIR /work

CMD ["bash"]
