FROM --platform=linux/arm64 debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY /src/main-uart-receive.cpp .

RUN g++ -std=c++17 -O2 main-uart-receive.cpp -o uart_rx

CMD ["./uart_rx"]
